---
- name: Build Icecast
  include_tasks: icecast.yml

- name: Install Liquidsoap (Focal)
  include_tasks: liquidsoap.yml
  when:
    - ansible_distribution_release == 'focal'

- name: Add Audiowaveform PPA
  apt_repository:
    repo: "ppa:chris-needham/ppa"
    update_cache: true

- name: Install Audiowaveform
  apt:
    name: audiowaveform
    install_recommends: false

- name: Install Flac
  apt:
    name: flac
    install_recommends: false

- name: Install Vorbis-Tools
  apt:
    name: vorbis-tools
    install_recommends: false
