version: '2'

services:
  nginx:
    image: azuracast/azuracast_nginx:latest
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - web
      - stations
    volumes:
      - .:/var/azuracast/www
    restart: always

  mariadb:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=azuracast
      - MYSQL_PASSWORD=azur4c457
      - MYSQL_DATABASE=azuracast
    restart: always

  influxdb:
    image: influxdb:alpine
    volumes:
      - influx_data:/var/lib/influxdb
    restart: always

  web:
    container_name: azuracast_web
    image: azuracast/azuracast_web:latest
    depends_on:
      - mariadb
      - influxdb
      - stations
    volumes:
      - .:/var/azuracast/www
      - cache_data:/var/azuracast/www_tmp
      - station_data:/var/azuracast/stations
    restart: always

  cron:
    container_name: azuracast_cron
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
    command: 'cron && tail -f /var/log/cron.log'
    restart: always

  cli:
    image: azuracast/azuracast_web:latest
    volumes_from:
      - web
    depends_on:
      - mariadb
      - influxdb
      - stations
    command: 'bash'

  stations:
    container_name: azuracast_stations
    image: azuracast/azuracast_stations:latest
    ports:
     - '8000-8500:8000-8500'
    volumes:
     - station_data:/var/azuracast/stations
    restart: always

volumes:
  db_data: {}
  influx_data: {}
  station_data: {}
  cache_data: {}