services:
  frontend:
    container_name: azuracast_frontend
    build:
      context: ./frontend
    user: "${AZURACAST_PUID:-1000}:${AZURACAST_PGID:-1000}"
    volumes:
      - $PWD/frontend:/data/frontend
      - $PWD/translations:/data/translations
      - $PWD/web/static:/data/web/static
