---
- hosts: all
  become: true

  vars:
    util_base: "{{ playbook_dir | dirname }}"
    www_base: "{{ util_base | dirname }}"
    app_base: "{{ www_base | dirname }}"
    tmp_base: "{{ app_base }}/www_tmp"
    app_env: "production"
    update_mode: true
    update_revision: 1

  environment:
    DEBIAN_FRONTEND: noninteractive

  roles:
    - role: "init"

    - role: "azuracast-config"

    - role: "azuracast-radio"
      when: update_revision|int < 94

    - role: "supervisord"

    - role: "mariadb"
      when: update_revision|int < 87

    - role: "nginx"
      when: update_revision|int < 90

    - role: "beanstalkd"
      when: update_revision|int < 87

    - role: "sftpgo"
      when: update_revision|int < 87

    - role: "php"
      when: update_revision|int < 87

    - role: "composer"

    - role: "ufw"
      when: update_revision|int < 86

    - role: "dbip"
      when: update_revision|int < 51

    - role: "azuracast-cron"
      when: update_revision|int < 87

    - role: "services"

    - role: "azuracast-build"

    - role: "azuracast-setup"
