---
  - name: Update apt
    sudo: yes
    apt:  update_cache=yes

  - name: Install system packages
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items:
      - curl
      - wget
      - build-essential
      - python-software-properties
      - pwgen